version: '3.7'
x-icon: docker
services:
  # Web-based file manager (Quantum fork)
  # https://github.com/gtsteffaniak/filebrowser
  filebrowser:
    image: gtstef/filebrowser:latest
    user: 1000:1000
    environment:
      - FILEBROWSER_CONFIG=data/config.yaml
    volumes:
      - /mnt/nvme/apps:/mnt/apps
      - /mnt/nvme/games:/mnt/games
      - /mnt/hdd/media:/mnt/media
      - /mnt/scratch/downloads:/mnt/downloads
      - @data:/home/filebrowser/data
    x-features:
      - domain: files
      - homepage:
          group: System
          description: File management
          weight: 20

  # Real-time Docker log viewer
  # https://dozzle.dev/
  dozzle:
    image: amir20/dozzle:latest
    user: 1000:999
    volumes:
      - @docker
    environment:
    - DOZZLE_ENABLE_ACTIONS=true
    - DOZZLE_ENABLE_SHELL=true
    x-features:
      - domain:
          subdomain: docker
          port: 8080
      - homepage:
          group: System
          description: Container management
          weight: 30

  # Automatic container updates
  # https://containrrr.dev/watchtower/
  watchtower:
    image: containrrr/watchtower
    user: 1000:999
    environment:
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_NOTIFICATION_URL=$WATCHTOWER_NOTIFICATION_URL
      - WATCHTOWER_WARN_ON_HEAD_FAILURE=never
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_HTTP_API_TOKEN
    volumes:
      - @docker
      - @config.json:ro
    x-features:
      - disable-watchtower:

  # Docker socket proxy for security
  # https://github.com/Tecnativa/docker-socket-proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - @docker
