version: '3.7'
services:
  backrest:
    image: garethgeorge/backrest:latest
    volumes:
      - @data
      - @config
      - /mnt/scratch/cache/backrest:/cache
      - /mnt/nvme/apps:/mnt/nvme/apps
      - /mnt/nvme/games:/mnt/nvme/games
      - /mnt/nvme/backups:/repos
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
    x-features:
      - domain:
          subdomain: restic
          port: 9898
      - homepage:
          group: Jobs
          description: Restic backups
          weight: 20

  olivetin:
    image: jamesread/olivetin:latest
    user: 1000:999
    volumes:
      - @config
      - @docker
    x-features:
      - domain:
          subdomain: olivetin
          port: 1337
      - homepage:
          group: Jobs
          description: Interactive tasks
          weight: 10
